#!/bin/sh

set -euo pipefail

# Initialization - load function handler
echo "INITIALIZING: LAMBDA_TASK_ROOT: $LAMBDA_TASK_ROOT _HANDLER: $_HANDLER pwd: $(pwd) ls: $(ls -al)"
# source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"
echo $(cat /etc/os-release)

echo $(ls -al /usr/lib64)

export LD_LIBRARY_PATH="/var/task/lib:/opt/lib:${LD_LIBRARY_PATH}"

echo "ABOUT TO INVOKE HANDLER"
./target/scala-2.11/main-out
echo "HANDLER DONE?"
