#!/bin/bash
set -o nounset
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
LAMBDA_ROLE_ARN=$LAMBDA_ROLE_ARN
docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e LAMBDA_ROLE_ARN -it native-lambda:latest ./invoke.sh "$@"